# GitHub Sponsors configuration
# These are supported funding model platforms

github: [ersinkoc]
# patreon: username
# open_collective: fluxupload
# ko_fi: username
# tidelift: npm/fluxupload
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://www.buymeacoffee.com/username']
